import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// POST /api/pipeline/script-edit — the animation pipeline reports the narration
// lines it regenerated, so they show up (auto-applied + GREEN) in the script view.
// Auth: CRON_SECRET bearer (a machine caller, like /api/pipeline/event).
// Body: { video? | projectId?, source_url?, edits: [{ original_text, suggested_replacement, reason? }] }
//
// For each edit we replace original_text -> suggested_replacement in Project.script
// (so the script reflects the new voiceover) and record a PendingScriptEdit row with
// status 'auto_applied'. That status renders GREEN in the script view exactly like an
// accepted edit, but — unlike 'accepted' — it is NOT surfaced in the "awaiting
// re-recording" queue, because the pipeline already regenerated the audio.

export const maxDuration = 30;

function authorized(req: NextRequest): boolean {
  const auth = req.headers.get('authorization');
  return !!auth && !!process.env.CRON_SECRET && auth === `Bearer ${process.env.CRON_SECRET}`;
}

export async function POST(req: NextRequest) {
  if (!authorized(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  try {
    const body = await req.json();
    const { video, projectId, source_url, edits } = body ?? {};
    if (!Array.isArray(edits) || edits.length === 0) {
      return NextResponse.json({ error: 'edits[] required' }, { status: 400 });
    }

    // Resolve the project by id, else by title (same as /api/pipeline/event).
    let project = projectId
      ? await prisma.project.findUnique({ where: { id: projectId }, select: { id: true, script: true } })
      : null;
    if (!project && video) {
      project = await prisma.project.findFirst({
        where: { title: video },
        orderBy: { updated_at: 'desc' },
        select: { id: true, script: true },
      });
    }
    if (!project) {
      return NextResponse.json(
        { error: `No project for video "${video ?? projectId ?? '(none)'}"` },
        { status: 404 }
      );
    }

    let script = project.script ?? '';
    const now = new Date();
    let applied = 0;
    const unmatched: string[] = [];

    for (const e of edits) {
      const oldText = typeof e?.original_text === 'string' ? e.original_text : '';
      const newText = typeof e?.suggested_replacement === 'string' ? e.suggested_replacement : '';
      if (!newText.trim()) continue;

      // Update the script blob: swap the old wording for the new (first occurrence),
      // so the script matches the new voiceover and the green highlight can anchor to it.
      if (oldText && script.includes(oldText)) {
        script = script.replace(oldText, newText);
        applied++;
      } else if (!script.includes(newText)) {
        // Couldn't place it (script diverged from the film's VO wording). Still record
        // the change below so it's visible; it just won't inline-highlight until matched.
        unmatched.push(oldText || newText);
      }

      // Idempotent re-runs: skip an identical auto_applied row if one already exists.
      const dup = await prisma.pendingScriptEdit.findFirst({
        where: { project_id: project.id, status: 'auto_applied', suggested_replacement: newText },
        select: { id: true },
      });
      if (dup) continue;

      await prisma.pendingScriptEdit.create({
        data: {
          project_id: project.id,
          source_url: typeof source_url === 'string' && source_url ? source_url : 'animation-pipeline',
          original_text: oldText,
          suggested_replacement: newText,
          reason:
            typeof e?.reason === 'string' && e.reason
              ? e.reason
              : 'Narration regenerated by the animation pipeline.',
          severity: 'minor',
          category: 'vo_regenerated',
          status: 'auto_applied',
          detected_at: now,
          resolved_at: now,
        },
      });
    }

    if (applied > 0) {
      await prisma.project.update({ where: { id: project.id }, data: { script } });
    }

    return NextResponse.json({ projectId: project.id, applied, unmatched });
  } catch (error) {
    console.error('pipeline/script-edit error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
